// src/utils/reportExporter.js
import { jsPDF } from 'jspdf';
import { formatCurrency } from './currency';

let jsPDFInstance = null;

// Dynamically load jsPDF
const getJsPDF = async () => {
  if (!jsPDFInstance) {
    const { jsPDF } = await import('jspdf');
    jsPDFInstance = jsPDF;
  }
  return jsPDFInstance;
};

export const generatePDF = async (reportData, filename) => {
  try {
    const jsPDF = await getJsPDF();
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const margin = 20;
    let yPos = margin;
    
    // Title
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(41, 128, 185);
    doc.text(reportData.metadata.title, pageWidth / 2, yPos, { align: 'center' });
    yPos += 10;
    
    // Report info
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated: ${new Date(reportData.metadata.generated).toLocaleString()}`, pageWidth / 2, yPos, { align: 'center' });
    yPos += 5;
    doc.text(`Type: ${reportData.metadata.type} | Date Range: ${reportData.metadata.dateRange}`, pageWidth / 2, yPos, { align: 'center' });
    yPos += 15;
    
    // Summary section
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text('SUMMARY', margin, yPos);
    yPos += 10;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    // Summary in two columns
    const leftColumn = margin;
    const rightColumn = pageWidth / 2 + 10;
    const currencyCode = reportData?.metadata?.currency || reportData?.currency || 'USD';
    
    // Left column
    doc.text(`Total Invoices: ${reportData.summary.totalInvoices}`, leftColumn, yPos);
    doc.text(`Total Customers: ${reportData.summary.totalCustomers}`, leftColumn, yPos + 8);
    doc.text(`Total Revenue: ${formatCurrency(reportData.summary.totalRevenue, currencyCode)}`, leftColumn, yPos + 16);
    doc.text(`Paid Invoices: ${reportData.summary.paidInvoices}`, leftColumn, yPos + 24);
    
    // Right column
    doc.text(`Pending Invoices: ${reportData.summary.pendingInvoices}`, rightColumn, yPos);
    doc.text(`Overdue Invoices: ${reportData.summary.overdueInvoices}`, rightColumn, yPos + 8);
    doc.text(`Draft Invoices: ${reportData.summary.draftInvoices}`, rightColumn, yPos + 16);
    doc.text(`Active Customers: ${reportData.summary.activeCustomers}`, rightColumn, yPos + 24);
    
    yPos += 35;
    
    // Check if we need a new page
    if (yPos > 250) {
      doc.addPage();
      yPos = margin;
    }
    
    // Invoice Status Breakdown
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('INVOICE STATUS BREAKDOWN', margin, yPos);
    yPos += 10;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    const statuses = [
      { label: 'Draft', value: reportData.breakdown.byStatus.draft },
      { label: 'Sent', value: reportData.breakdown.byStatus.sent },
      { label: 'Paid', value: reportData.breakdown.byStatus.paid },
      { label: 'Overdue', value: reportData.breakdown.byStatus.overdue },
      { label: 'Pending', value: reportData.breakdown.byStatus.pending },
      { label: 'Cancelled', value: reportData.breakdown.byStatus.cancelled }
    ];
    
    statuses.forEach((status, index) => {
      const rowY = yPos + (index * 8);
      doc.text(`${status.label}:`, margin, rowY);
      doc.text(`${status.value}`, margin + 40, rowY);
      const percentage = ((status.value / reportData.summary.totalInvoices) * 100 || 0).toFixed(1);
      doc.text(`${percentage}%`, margin + 60, rowY);
    });
    
    yPos += (statuses.length * 8) + 15;
    
    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by Ledgerly Invoice System', pageWidth / 2, pageHeight - 20, { align: 'center' });
    doc.text(`Page 1 of 1 • ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, pageWidth / 2, pageHeight - 15, { align: 'center' });
    
    // Save the PDF
    doc.save(filename);
    
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw error;
  }
};

export const generateExcelContent = (reportData) => {
  const currencyCode = reportData?.metadata?.currency || reportData?.currency || 'USD';
  const rows = [
    ['Report:', reportData.metadata.title],
    ['Generated:', new Date(reportData.metadata.generated).toLocaleString()],
    ['Type:', reportData.metadata.type],
    ['Format:', reportData.metadata.format],
    ['Date Range:', reportData.metadata.dateRange],
    [],
    ['SUMMARY', '', ''],
    ['Total Invoices:', reportData.summary.totalInvoices],
    ['Total Customers:', reportData.summary.totalCustomers],
    ['Total Revenue:', formatCurrency(reportData.summary.totalRevenue, currencyCode)],
    ['Paid Invoices:', reportData.summary.paidInvoices],
    ['Pending Invoices:', reportData.summary.pendingInvoices],
    ['Overdue Invoices:', reportData.summary.overdueInvoices],
    ['Draft Invoices:', reportData.summary.draftInvoices],
    ['Active Customers:', reportData.summary.activeCustomers],
    ['New Customers (Last 30 Days):', reportData.summary.newCustomersLast30Days],
    [],
    ['INVOICE BREAKDOWN BY STATUS', '', ''],
    ['Draft:', reportData.breakdown.byStatus.draft],
    ['Sent:', reportData.breakdown.byStatus.sent],
    ['Paid:', reportData.breakdown.byStatus.paid],
    ['Overdue:', reportData.breakdown.byStatus.overdue],
    ['Pending:', reportData.breakdown.byStatus.pending],
    ['Cancelled:', reportData.breakdown.byStatus.cancelled],
    [],
    ['REVENUE BY STATUS', '', ''],
    ['Paid Revenue:', formatCurrency(reportData.breakdown.revenueByStatus.paid, currencyCode)],
    ['Pending Revenue:', formatCurrency(reportData.breakdown.revenueByStatus.pending, currencyCode)],
    ['Overdue Revenue:', formatCurrency(reportData.breakdown.revenueByStatus.overdue, currencyCode)],
    [],
    ['TOP CUSTOMERS', 'Invoices', 'Total Amount'],
    ...reportData.breakdown.byCustomer.slice(0, 10).map(cust => [
      cust.name,
      cust.totalInvoices,
      formatCurrency(cust.totalAmount, currencyCode)
    ]),
    [],
    ['MONTHLY TREND', 'Month', 'Revenue', 'Invoices', 'Average per Invoice'],
    ...reportData.breakdown.monthlyTrend.map(month => {
      const avgInvoice = month.invoices > 0 ? (month.revenue / month.invoices) : 0;
      return [
        month.month,
        formatCurrency(month.revenue, currencyCode),
        month.invoices,
        formatCurrency(avgInvoice, currencyCode)
      ];
    })
  ];

  return rows.map(row => row.join(',')).join('\n');
};

export const generateCSVContent = (reportData) => {
  return generateExcelContent(reportData);
};

export const generateHTMLContent = (reportData) => {
  // Same HTML content as before (too long to include here)
  // You can copy this from the previous code
  return `<!DOCTYPE html>...`;
};

export const generateTextContent = (reportData) => {
  const title = reportData.metadata.title;
  const date = new Date(reportData.metadata.generated).toLocaleString();
  const currencyCode = reportData?.metadata?.currency || reportData?.currency || 'USD';
  
  return `
==================================================================
                          ${title}
==================================================================

Generated: ${date}
Report Type: ${reportData.metadata.type}
Format: ${reportData.metadata.format}
Date Range: ${reportData.metadata.dateRange}

SUMMARY
==================================================================
Total Invoices: ${reportData.summary.totalInvoices}
Total Customers: ${reportData.summary.totalCustomers}
Total Revenue: ${formatCurrency(reportData.summary.totalRevenue, currencyCode)}
Paid Invoices: ${reportData.summary.paidInvoices}
Pending Invoices: ${reportData.summary.pendingInvoices}
Overdue Invoices: ${reportData.summary.overdueInvoices}
Draft Invoices: ${reportData.summary.draftInvoices}
Active Customers: ${reportData.summary.activeCustomers}
New Customers (Last 30 Days): ${reportData.summary.newCustomersLast30Days}

==================================================================
Generated by Ledgerly Invoice System
${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}
==================================================================
  `;
};
